// Compiles the swap engine to WebAssembly and stages it for Vite.
//
// Two things are baked in at build time rather than configured at run time:
// the build name, and the address of the deployed program. The program's
// address comes from its keypair, which is generated by the first build and
// changes whenever the program is deployed somewhere new -- so reading it here,
// from the file the deploy used, is what keeps the page's default pointed at
// the program that is actually on the chain. It stays a default: the page's
// settings can name any deployment, and an offer naming a different one is
// refused rather than quietly accepted.

import { execFileSync } from 'node:child_process'
import { copyFileSync, existsSync, mkdirSync, readFileSync, statSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'

const here = dirname(fileURLToPath(import.meta.url))
const ui = join(here, '..')
const root = join(ui, '..')
const wasmDir = join(root, 'wasm')
const outDir = join(ui, 'public')

const build = process.env.SOLZEN_BUILD ?? 'dev'

function programId() {
  if (process.env.SOLZEN_PROGRAM) return process.env.SOLZEN_PROGRAM
  const keypair = join(root, 'program/target/deploy/solzen_htlc-keypair.json')
  if (!existsSync(keypair)) {
    console.warn(
      'build-wasm: no program keypair found, so the page will start with no program id set.\n' +
        '            Build and deploy the program first, or set SOLZEN_PROGRAM.',
    )
    return ''
  }
  // The keypair file is the 64-byte ed25519 secret key; its last 32 bytes are
  // the public key, which is the program's address. Deriving it here avoids
  // needing the Solana CLI at build time.
  const secret = Uint8Array.from(JSON.parse(readFileSync(keypair, 'utf8')))
  return base58(secret.slice(32))
}

const ALPHABET = '123456789ABCDEFGHJKLMNPQRSTUVWXYZabcdefghijkmnopqrstuvwxyz'
function base58(bytes) {
  let x = 0n
  for (const b of bytes) x = x * 256n + BigInt(b)
  let out = ''
  while (x > 0n) {
    out = ALPHABET[Number(x % 58n)] + out
    x /= 58n
  }
  for (const b of bytes) {
    if (b !== 0) break
    out = ALPHABET[0] + out
  }
  return out
}

function goEnv(name) {
  return execFileSync('go', ['env', name], { encoding: 'utf8' }).trim()
}

mkdirSync(outDir, { recursive: true })

const program = programId()
console.log(`build-wasm: build=${build} program=${program || '(unset)'}`)

execFileSync(
  'go',
  [
    'build',
    '-trimpath',
    '-ldflags',
    `-s -w -X main.BuildName=${build} -X main.SolProgramID=${program}`,
    '-o',
    join(outDir, 'solzen.wasm'),
    '.',
  ],
  { cwd: wasmDir, stdio: 'inherit', env: { ...process.env, GOOS: 'js', GOARCH: 'wasm' } },
)

// Go's own JS shim. It has to match the compiler that produced the module, so
// it is copied from this GOROOT on every build rather than vendored once and
// left to drift.
const goroot = goEnv('GOROOT')
const shim = [join(goroot, 'lib', 'wasm', 'wasm_exec.js'), join(goroot, 'misc', 'wasm', 'wasm_exec.js')].find(
  (p) => existsSync(p),
)
if (!shim) throw new Error(`could not find wasm_exec.js under ${goroot}`)
copyFileSync(shim, join(outDir, 'wasm_exec.js'))

const size = statSync(join(outDir, 'solzen.wasm')).size
console.log(`build-wasm: ${(size / 1e6).toFixed(1)} MB -> ui/public/solzen.wasm`)
